[build]
  command = "npm run build"
  publish = "dist"

[functions]
  nodeVersion = "18"

[[plugins]]
  package = "@netlify/plugin-cache"

[[plugins]]
  package = "@netlify/plugin-cache-playwright"

[build.environment]
  PLAYWRIGHT_BROWSERS_PATH = "0"